### ISSUE TITLE
website

### ISSUE THREAD

**Issue by gelones** [MinoriBot/Website#1]
what is the purpose of this repository?

Can we use the project for our bots by making modifications?

@gonzyui

**Comment by gonzyui** [comment]
yeah you can but this repo isn't the full website

**Comment by gelones** [comment]
> yeah you can but this repo isn't the full website

Thanks, I'll study it to maybe use it, adding other pages to it, thanks for the project, you could attach a license.
@gonzyui

**Comment by gonzyui** [comment]
no need for a license as the code will be changed soon but thanks
